apiVersion: harness.io/v1
kind: Workflow
name: TriggerGithubPipeline-wkflow
identifier: TriggerGithubPipelinewkflow
type: template-based workflow
owner: group:account/_account_all_users
projectIdentifier: CSDemo
orgIdentifier: WiproPOC
metadata:
  description: Workflow for triggering the Harness GitHub CI/CD pipeline that executes the GitHub Actions build.yml workflow
  tags:
    - Github
    - Harness
    - IDP
    - FullStack
    - GitHubActions
spec:
  lifecycle: production
  output:
    links:
      - title: Harness Pipeline Execution
        url: ${{ steps.trigger.output.PipelineUrl }}
  parameters:
    - title: Trigger GitHub Actions Pipeline
      required:
        - service_name
        - confirmation
        - token
      properties:
        service_name:
          title: Service Name
          type: string
          description: Mention the project or service name for this pipeline execution
          default: Harness-Wipro-PoC
        confirmation:
          title: Execution Confirmation
          type: string
          description: Select TRIGGER to confirm pipeline execution
          enum:
            - TRIGGER
          default: TRIGGER
        token:
          title: Harness Token
          type: string
          description: Harness authentication token used by IDP to execute the pipeline
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Trigger Harness Pipeline for GitHub Actions
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/2KolbecvR0aAcgQ5uXBObA/module/idp/orgs/WiproPOC/projects/CSDemo/pipelines/swsTest1triggergithubactions/pipeline-studio/?storeType=INLINE
        inputset:
          service_name: ${{ parameters.service_name }}
        apikey: ${{ parameters.token }}
        hidePipelineURLLog: true
        showOutputVariables: true
